### ISSUE TITLE
Lazy Evalution

### ISSUE THREAD

**Issue by gordon-to** [ipavlic/apex-lambda#1]
Filter could have an applyLazy. If I'm looking for the first 10 accounts that match some query filtering the whole list is wasteful. You could return an Iterable instead so I could consume as many or as few as I needed.

**Comment by ipavlic** [comment]
This can be implemented through an `Iterable`. `Filter.[...].applyLazy()` would return e.g. `FilterResult` of type `Iterable<SObject>` as you say. To use it you would have to do something like:

    FilterResult result = Filter.[...].applyLazy();
    Iterator<SObject> resultIterator = result.iterator();
    while (resultIterator.hasNext()) {
        // do something
    }

I’ve implemented it and can push it. However, would you not rather prefer something like `Filter.[...].applyFirst(Integer count)` which would give you up to first `count` matches?

**Comment by xMrWhite** [comment]
The other benefit of the first approach is that the record will be "warm" Salesforce will have just accessed the record and will have it in cache memory so that further accesses to that record will be faster, by not processing the filter for the whole list, but one record at a time you avoid evicting records from the cache before you are finished with them. This is especially true if I am getting the first `count` records from a list of size `count * 100` where records are sparse.

**Comment by ipavlic** [comment]
cf5a766b02e4d88a2e8619f23c74515458ed380f contains lazy filtering implementation. I’m still not sure how useful the optimization is for general use, but those that **do** want to use it, you can write something like:

    Iterable<Account> lazyResults = (Iterable<Account>) Filter.[...].applyLazy();
    Iterator<Account> iterator = lazyResults.iterator();
    while (iterator.hasNext()) {
        Account acc = iterator.next();
        // do something with `acc`
    }

**Comment by ipavlic** [comment]
I'm reopening this due to the redesign done in c05cfb6 dropping previously implemented functionality.

**Comment by ipavlic** [comment]
This could potentially be reimplemented with the following programme:

First, accumulate `SObjectToSObjectFunctions` to apply in Collection instead of applying them directly. This would convert it to a proper view.

For example, when `Collection.filter(...)` is called, a new `Collection` with original record list and filter function is returned instead of a `Collection` a filtered list of original records. If `remove()` is invoked for the returned collection, a new `Collection` is again returned, this time with both functions.

| Implemetation | `.filter(...)` returns `Collection` with | `.filter(...).remove(...)` returns `Collection` with |
| --- | --- | --- |
| Current | list of filtered original records | list of remaining records | 
| Suggested | full list of original records, `[filter]` function specification list | full list of original records, `[filter, remove]` function specification list | 

Second, apply accumulated functions when `.as...` functions are called:

| Implemetation | `asList()` implementation |
| --- | --- |
| Current | return a new `List` of current records | 
| Suggested | apply all functions in order, then return a new `List` of obtained records | 

Third, implemented above in a `LazyCollection` which would implement a common `LambdaCollection` interface. This would clearly indicate that the results are computed lazily – two calls will mean two lazy applications.

Fourth, see whether `Transform` should no longer modify the original record, but instead return a copy obtained with `clone`. The decision to modify the original was made to reduce memory and CPU usage. This could also be done on a list level as well – a lazy list might clone first and then pass to `Transform`. It could also be done on a transform, as an additional parameter; `Transform.record(record, shouldClone)`.

**Comment by ipavlic** [comment]
It's been a long time coming, but I've finally added a skeleton for lazy evaluation similar to Java's Stream in cdfe677479e9c9e0fadb745263efa1156c13b8bb.
