### ISSUE TITLE
How to pluck relational attribute?

### ISSUE THREAD

**Issue by jeffrey008** [ipavlic/apex-lambda#3]
I am trying to use pluck to get a list of email. Here is what I tried. Is there any way we can do this? Thanks.

```apex
List<PermissionSetAssignment> psa = [SELECT Id, AssigneeId, Assignee.Email
        FROM PermissionSetAssignment
   ];
List<String> emails = Pluck.strings(psa, PermissionSetAssignment.Assignee.Email);
```

**Comment by ipavlic** [comment]
That's not possible (yet). Field tokens do not store any information on the relation through which they were obtained.`Foo.Name` is the same `Schema.SObjectField` instance as `Foo.Child.Parent.Name`. 

You can call `getDescribe()` on it, but the result of that call does not tell you anything about how you initially got to the field. This relationship is important because it would allow you to walk it through relationship levels to get to the field on the instance.

For example, to get to the `Email` field of an assignee on a permission set assignment, one would need to start at `PermissionSetAssignment` instance, `getSObject` on it to get to the `User` instance, and `get` the `Email` field on the user to pluck it. Since the `Pluck.strings` only gets the `Email` field instance, with no relational information, it cannot know which `Email` you would like, and tries to extract it from the initial object (`PermissionSetAssignment`).

This could be solved by providing `Pluck` methods which take `String` instances instead of `SObjectField` as parameters, because they would preserve the entire relationship.

Multiple children (like_Opportunity Line Items_ on _Opportunity_) complicate the issue a bit, but not terribly – it would either be documented that you would pluck from all the children, or a special "language" would have to be defined. For example, `Opportunity.OpportunityLineItems[0].Name` might mean pluck names of all first opportunity line items. I don't believe that makes much sense though.

**Comment by ipavlic** [comment]
This should now work for `Pluck`.

**Comment by jeffrey008** [comment]
OMG you are so great <3
