### ISSUE TITLE
Are there any plans to consume a collection of iterable custom classes?

### ISSUE THREAD

**Issue by samuel012** [ipavlic/apex-lambda#6]
Right now the Collection class only caters to a list of sobjects. Are there plans to cater to list of custom classes? My use case right now is to use methods like pluck against wrapper classes that wraps responses from API callouts.

For example, my API response wrapper class contains a `List<Shipments>`. I wanted to iterate over that list of Shipment records and pluck the `shipment_id` field. Do you foresee that use case in your roadmap?

**Comment by ipavlic** [comment]
Apex doesn't support generic classes/methods, has no reflection and is not very dynamic, so there is no general way to extract a property. `SObject` is special because its properties can be obtained with a `get` method, not available otherwise. One way language drawbacks could be worked around is to serialize into JSON, unserialize into an untyped map and then grab the property. I would imagine this is quite inefficient for a larger amount of objects, but would have to check just how much.

**Comment by ipavlic** [comment]
Direct field access for 10,000 shipments with just a random `Integer` "serial number" field takes ~50 ms to pluck values, while the serialization roundtrip takes ~1800 ms. My answer is therefore _no_, I don't plan to include this use case.
